root: "input/"
train_label_file: "train_labels.csv"
train_path: "input/train/"
test_path: "input/test/"

lr: 0.001
epochs: 300
patience: 50
seed: 42

model_path: "effnet_model.pth"
load_model_path: "model/effnet_model.pth"
project: "kaggle-img-match"
experiment_name: "effnet"
model_name: "effnet"