root: "input/"
train_label_file: "train_labels.csv"
train_path: "input/train"
test_path: "input/test"

lr: 0.001
epochs: 10
patience: 10
seed: 42

model_path: "baseline_model.pth"
load_model_path: "model/baseline_model.pth"
project: "kaggle-img-match"
experiment_name: "baseline"
model_name: "baseline"